export const TOGGLE_ISLOADING = "TOGGLE_ISLOADING";
export const LOGIN = "LOGIN";
export const ALERT_MESSAGE = "ALERT_MESSAGE";
export const USER_DETAILS = "USER_DETAILS";
export const USER_UPDATE = "USER_UPDATE";
export const CLEAR_MSG = "CLEAR_MSG";
export const CLEAR_USER_DETAILS = "CLEAR_USER_DETAILS";

// CATEGORY
export const FETCH_CATEGORY = "FETCH_CATEGORY";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const TOGGLE_ISLOADING_CATEGORY = "TOGGLE_ISLOADING_CATEGORY";

// CATEGORYNATIVENAME
export const ACTIVE_CATEGORY = "FETCH_CATEGORY_NATIVE_NAME";
export const CREATE_CATEGORY_NATIVE_NAME = "CREATE_CATEGORY_NATIVE_NAME";
export const DELETE_CATEGORY_NATIVE_NAME = "DELETE_CATEGORY_NATIVE_NAME";
export const UPDATE_CATEGORY_NATIVE_NAME = "UPDATE_CATEGORY_NATIVE_NAME";
export const TOGGLE_ISLOADING_CATEGORY_NATIVE =
  "TOGGLE_ISLOADING_CATEGORY_NATIVE";

// ETHNIC
export const FETCH_ETHNIC = "FETCH_ETHNIC";
export const CREATE_ETHNIC = "CREATE_ETHNIC";
export const DELETE_ETHNIC = "DELETE_ETHNIC";
export const UPDATE_ETHNIC = "UPDATE_ETHNIC";
export const TOGGLE_ISLOADING_ETHNIC = "TOGGLE_ISLOADING_ETHNIC";

// LANGUAGE
export const FETCH_LANGUAGE = "FETCH_LANGUAGE";
export const FETCH_LANGUAGE_PROVERBS = "FETCH_LANGUAGE_PROVERBS";
export const FETCH_LANGUAGE_ETHNICS = "FETCH_LANGUAGE_ETHNICS";
export const CREATE_LANGUAGE = "CREATE_LANGUAGE";
export const UPDATE_LANGUAGE = "UPDATE_LANGUAGE";
export const DELETE_LANGUAGE = "DELETE_LANGUAGE";

export const PASSWORD_CHANGE = "PASSWORD_CHANGE";

//PROVERB
export const SAVE_PROVERBS = "SAVE_PROVERBS";
export const SEARCH_PROVERB = "SEARCH_PROVERB";
export const SAVE_PROVERBS_VIEW = "SAVE_PROVERBS_VIEW";
export const CLEAR_PROVERBS = "CLEAR_PROVERBS";
export const FETCH_DASHBOARD_PROVERBS = "FETCH_DASHBOARD_PROVERBS";
export const SAVE_LIKELIHOOD_PROVERBS = "SAVE_LIKELIHOOD_PROVERBS";
export const CLEAR_LIKELIHOOD_PROVERBS = "CLEAR_LIKELIHOOD_PROVERBS";
export const ACTIVE_PROVERBS = "ACTIVE_PROVERBS";
export const CLEAR_SELECTED = "CLEAR_SELECTED";
export const UPDATE_PROVERB_CATEGORY = "UPDATE_PROVERB_CATEGORY";
export const ADD_NEW_PROVERB_TRANSLITERATION =
  "ADD_NEW_PROVERB_TRANSLITERATION";
export const ADD_NEW_PROVERB_INTERPRETATION = "ADD_NEW_PROVERB_INTERPRETATION";
export const ADD_NEW_PROVERB_COMMENT = "ADD_NEW_PROVERB_COMMENT";
export const DELETE_PROVERB_TRANSLITERATION = "DELETE_PROVERB_TRANSLITERATION";
export const DELETE_PROVERB_INTERPRETATION = "DELETE_PROVERB_INTERPRETATION";
export const DELETE_PROVERB_COMMENT = "DELETE_PROVERB_COMMENT";
export const UPDATE_PROVERB_TRANSLITERATION = "UPDATE_PROVERB_TRANSLITERATION";
export const UPDATE_PROVERB_INTERPRETATION = "UPDATE_PROVERB_INTERPRETATION";
export const UPDATE_PROVERB_COMMENT = "UPDATE_PROVERB_COMMENT";

export const ADD_PROVERBS_AUDIO = "ADD_PROVERBS_AUDIO";
export const DOWNLOAD_PROVERBS_AUDIO = "DOWNLOAD_PROVERBS_AUDIO";
export const DELETE_AUDIO = "DELETE_AUDIO";

export const CLEAR_PROVERB_MSG = "CLEAR_PROVERB_MSG";
export const ADD_NEW_PROVERB = "ADD_NEW_PROVERB";
export const UPDATE_PROVERB = "UPDATE_PROVERB";
export const DELETE_PROVERB = "DELETE_PROVERB";
export const ADD_FETCHED_PROVERBS = "ADD_FETCHED_PROVERBS";
export const DASHBOARD_COUNT = "DASHBOARD_COUNT";

// Users
export const CREATE_USER = "CREATE_USER";
export const UPDATE_USER = "UPDATE_USER";
export const FETCH_USERS = "FETCH_USERS";
export const FETCH_EACH_USER = "FETCH_EACH_USER";
export const USER_ALERT = "USER_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";
export const DELETE_USER = "DELETE_USER";
export const FETCH_PERMISSION = "FETCH_PERMISSION";
export const CLEAR_SELECTED_USER = "CLEAR_SELECTED_USER";

// PASSWORD
export const REQUEST_RESET_PASSWORD = "REQUEST_RESET_PASSWORD";
export const SET_NEW_PASSWORD = "SET_NEW_PASSWORD";

// PROVERB ROLES
export const FETCH_PROVERB_ADMIN_ROLES = "FETCH_PROVERB_ADMIN_ROLES";
export const CREATE_PROVERB_ADMIN_ROLES = "CREATE_PROVERB_ADMIN_ROLES";
export const UPDATE_PROVERB_ADMIN_ROLES = "UPDATE_PROVERB_ADMIN_ROLES";
export const DELETE_PROVERB_ADMIN_ROLES = "DELETE_PROVERB_ADMIN_ROLES";

// FAMILY ADMIN

export const CREATE_FAMILYADMIN_USER = "CREATE_FAMILYADMIN_USER";
export const UPDATE_FAMILYADMIN_USER = "UPDATE_FAMILYADMIN_USER";
export const FETCH_FAMILYADMIN_USERS = "FETCH_FAMILYADMIN_USERS";
export const FETCH_EACH_FAMILYADMIN_USER = "FETCH_EACH_FAMILYADMIN_USER";
export const USER_FAMILYADMIN_ALERT = "USER_FAMILYADMIN_ALERT";
export const CLEAR_FAMILYADMIN_ALERT = "CLEAR_FAMILYADMIN_ALERT";
export const DELETE_FAMILYADMIN_USER = "DELETE_FAMILYADMIN_USER";
export const CLEAR_SELECTED_FAMILYADMIN_USER =
  "CLEAR_SELECTED_FAMILYADMIN_USER";

//FAQ ACTION TYPES
export const CREATE_FAQ = "CREATE_FAQ";
export const UPDATE_FAQ = "UPDATE_FAQ";
export const DELETE_FAQ = "DELETE_FAQ";
export const ADD_FETCHED_FAQS = "ADD_FETCHED_FAQS";
export const ORDER_FAQS = "ORDER_FAQS";

// PACKAGES ACTION TYPES
export const CREATE_PACKAGE = "CREATE_PACKAGE";
export const UPDATE_PACKAGE = "UPDATE_PACKAGE";
export const DELETE_PACKAGE = "DELETE_PACKAGE";
export const ADD_FETCHED_PACKAGES = "ADD_FETCHED_PACKAGES";
export const UPDATE_FORM_DATA = "UPDATE_FORM_DATA";
export const SORT_PACKAGES = "SORT_PACKAGES";

// SUGGESTED PROVERBS ACTION TYPES
export const ADD_SUGGESTED_PROVERBS = "ADD_SUGGESTED_PROVERBS";
export const UPDATE_SUGGESTED_PROVERB = "UPDATE_SUGGESTED_PROVERB";

// SUGGESTED CORRECTION ACTION TYPES
export const ADD_CORRECTED_PROVERBS = "ADD_CORRECTED_PROVERBS";
export const ADD_SUGGESTED_CORRECTION = "ADD_SUGGESTED_CORRECTION";
export const UPDATE_CORRECTED_PROVERB = "UPDATE_SUGGESTED_PROVERB";

// PUSH NOTIFICATION
export const SEND_NOTIFICATION_REQUEST = "SEND_NOTIFICATION_REQUEST";

// SUBSCRIBER ACTIONS
export const FETCH_SUBSCRIBERS = "FETCH_SUBSCRIBERS";
export const SEARCH_SUBSCRIBERS = "SEARCH_SUBSCRIBERS";
export const FETCH_SUBSCRIPTION = "FETCH_SUBSCRIPTION";
export const ADMIN_UPDATE_USER = "ADMIN_UPDATE_USER";

//ACTIVE SUBSCRIBERS TYPES

export const FETCH_ACTIVE_SUBSCRIBERS = "FETCH_ACTIVE_SUBSCRIBERS";

export const ADD_ACTIVE_SUBSCRIBERS_STATUS = "DD_ACTIVE_SUBSCRIBERS_STATUS";

// ETHNIC FACT QUESTIONS ACTION TYPES
export const CREATE_QUESTION = "CREATE_QUESTION";
export const UPDATE_QUESTION = "UPDATE_QUESTION";
export const DELETE_QUESTION = "DELETE_QUESTION";
export const ADD_FETCHED_QUESTIONS = "ADD_FETCHED_QUESTIONS";
export const SORT_QUESTIONS = "SORT_PACKAGES";

//QUESTION MAPPING
export const FETCH_ETHNIC_MAPPED_QUESTIONS = "FETCH_ETHNIC_MAPPED_QUESTIONS";
export const FETCH_ALL_QUESTIONS = "FETCH_ALL_QUESTIONS";
export const IS_QUESTION_SAVED = "IS_QUESTION_SAVED";
export const FETCH_QUESTION_OPTIONS = "FETCH_QUESTION_OPTIONS";
export const CLEAR_CONTENT = "CLEAR_CONTENT";
export const IS_OPTION_SAVED = "IS_OPTION_SAVED";
export const IS_OPTION_DELETED = "IS_OPTION_DELETED";
export const IS_QUESTION_DELETED = "IS_QUESTION_DELETED";
export const FETCH_SINGLE_QUESTION = "FETCH_SINGLE_QUESTION";

//QUESTION MAPPING
export const FETCH_ALL_QUESTIONS_PROPERTY = "FETCH_ALL_QUESTIONS_PROPERTY";
export const IS_QUESTION_PROPERTY_SAVED = "IS_QUESTION_PROPERTY_SAVED";
export const IS_QUESTION_PROPERTY_DELETED = "IS_QUESTION_PROPERTY_DELETED";

// GENERATE QUESTION FOR A USER
export const GENERATE_QUESTION_A_USER = "GENERATE_QUESTION_A_USER";
export const GENERATE_QUESTION_ALL_USER = "GENERATE_QUESTION_ALL_USER";




//AFFILIATED LANGUAGE
export const CREATE_AFFILIATEDLANGUAGE = "CREATE_AFFILIATEDLANGUAGE";
export const DELETE_AFFILIATEDLANGUAGE= "DELETE_AFFILIATEDLANGUAGE";
export const FETCH_AFFILIATEDLANGUAGEBYID= "FETCH_AFFILIATEDLANGUAGEBYID";
export const RESET_AFFILIATE ="RESET_AFFILIATE";
